[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
CheckedSizeProduct = "1b2cc9da-92e3-4b71-9788-30fc110eefda"

[sources]
CheckedSizeProduct = {path = ".."}

[compat]
Documenter = "1"
CheckedSizeProduct = "1"
